### ISSUE TITLE
Add onTerrain parameter for FeatureStyle

### ISSUE THREAD

**Issue by flavignotte** [VirtualGeo/Mizar#2]
Add a onTerrain parameter for FeatureStyle, default value is "true"
The parameter is going to be used to select the "good" renderer to display lines : either the Tile..Renderer or the LineRenderer.
LineRenderer must use the altitude stored in the coordinates of the GeoJSON if it exists.

**Comment by cmourglia** [comment]
Closed by 3091698ae434b316f3fc4d1251375149846bbc68
