### ISSUE TITLE
Tesselate lines to follow the earth curvature (Great Circle)

### ISSUE THREAD

**Issue by flavignotte** [VirtualGeo/Mizar#4]
In LineRenderer, we should tesselate the lines according to the following properties : 

- MaxDistance : the maximum distance (in meter) between two successive points along a segment

- MaxStep : the maximum subdvision to apply according to max distance to avoid generating too many points on the line

**Comment by cmourglia** [comment]
Are there particular cases to test / be careful of ? Like going from -180° to 180°, etc.
